name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh' 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Lint Dockerfile using hadolint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Build docker image
      run: docker build .

